name: Pull Request Check
on:
  pull_request:
    branches:
      - master
    paths:
      - 'app/**'
      - 'gradle/**'
      - '.github/workflows/**'
      - '*.gradle.kts'
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Build APK with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleSnapshot